
###
# Create citiesPopList table so we can load data into it.
POST http://localhost:9925/
Content-Type: application/json
Authorization: Basic SERCX0FETUlOOnBhc3N3b3Jk

{
    "operation": "create_table",
    "table": "citiesPopList",
    "primary_key": "id"
}


###
# Create sunnyCloudyCityMatches table so we can load data into it.
POST http://localhost:9925/
Content-Type: application/json
Authorization: Basic SERCX0FETUlOOnBhc3N3b3Jk

{
    "operation": "create_table",
    "table": "sunnyCloudyCityMatches",
    "primary_key": "match_id"
}


###
# Import Cities & Population csv file via Operations API
# Data source: https://raw.githubusercontent.com/plotly/datasets/master/us-cities-top-1k.csv
POST http://localhost:9925/
Content-Type: application/json
Authorization: Basic SERCX0FETUlOOnBhc3N3b3Jk

{
  "operation": "csv_file_load",
  "action": "upsert",
  "database": "data",
  "table": "citiesPopList",
  "file_path": "/home/harperdb/hdb/data-for-hdb/us-cities-top-1k.csv"
}

###
# Check our table
# SELECT * FROM data.citiesPopList ORDER BY Population DESC LIMIT 3
GET http://localhost:9926/flight-ads-app/getCities?limit=5
Content-Type: application/json
Authorization: Basic SERCX0FETUlOOnBhc3N3b3Jk

###
# Run runMain route
GET http://localhost:9926/flight-ads-app/runMain
Content-Type: application/json
Authorization: Basic SERCX0FETUlOOnBhc3N3b3Jk
