# This file uses this VS Code extension, which is a simplified version of a tool like Postman
#    Name: REST Client  VS Code Extension Marketplace Link: https://marketplace.visualstudio.com/items?itemName=humao.rest-client

###
# Run runMain route
GET http://localhost:9926/flight-ads-app/runMain
Content-Type: application/json
Authorization: Basic SERCX0FETUlOOnBhc3N3b3Jk


###
# ## PREREQUISITE: Run Main fn.
# Check to see if sunnyCloudyCityMatches table was created from REST API.
POST http://localhost:9925/
Content-Type: application/json
Authorization: Basic SERCX0FETUlOOnBhc3N3b3Jk

{
    "operation": "sql",
    "sql": "SELECT * FROM data.sunnyCloudyCityMatches"
}

###
# ## PREREQUISITE: Run Main fn.
# # Check to weatherFlightSets table-- The table with sun/cloud city, plus iata.
POST http://localhost:9925/
Content-Type: application/json
Authorization: Basic SERCX0FETUlOOnBhc3N3b3Jk

{
    "operation": "sql",
    "sql": "SELECT * FROM data.weatherFlightSets LIMIT 5"
}










###
# Run generateIataForFlights route
# GET http://localhost:9926/flight-ads-app/generateIataForFlights
# Content-Type: application/json
# Authorization: Basic SERCX0FETUlOOnBhc3N3b3Jk


###
# # Testing....
# POST http://localhost:9925/
# Content-Type: application/json
# Authorization: Basic SERCX0FETUlOOnBhc3N3b3Jk

# {
#     "operation": "sql",
#     "sql": "CREATE TEMPORARY TABLE TempCloudyCities AS SELECT match_id, cloudy_orig_city, iata AS cloudy_orig_airportCode FROM sunnyCloudyCityMatches JOIN airportIataCodes ON sunnyCloudyCityMatches.cloudy_orig_city = airportIataCodes.city"
# }




###
###
# # test
# POST http://localhost:9925/
# Content-Type: application/json
# Authorization: Basic SERCX0FETUlOOnBhc3N3b3Jk

# {
#     "operation": "sql",
#     "sql": "CREATE TABLE weatherFlightSets AS
#           SELECT
#               data.sunnyCloudyCityMatches.match_id AS weatherFlightSet_id,
#               data.sunnyCloudyCityMatches.cloudy_orig_city,
#               originAirportCodes.iata AS cloudy_orig_airportCode,
#               data.sunnyCloudyCityMatches.sunny_dest_city,
#               destinationAirportCodes.iata AS sunny_dest_airportCode
#           FROM
#               data.sunnyCloudyCityMatches
#           JOIN
#               data.airportIataCodes originAirportCodes ON data.sunnyCloudyCityMatches.cloudy_orig_city = originAirportCodes.city
#           JOIN
#               data.airportIataCodes destinationAirportCodes ON data.sunnyCloudyCityMatches.sunny_dest_city = destinationAirportCodes.city"
# }